import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const noto = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "public/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "pwa-test",
  },
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "#FFFFFF",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
      <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" />
    </html>
  );
}
